// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT_vTsBBLcvbMjOSejgBk_d1DNhMjfXL8',
    appId: '1:202435906700:web:cc6fefec1561bce8a23fa9',
    messagingSenderId: '202435906700',
    projectId: 'forpartum-app',
    authDomain: 'forpartum-app.firebaseapp.com',
    storageBucket: 'forpartum-app.appspot.com',
    measurementId: 'G-LN33JD06C0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK2FUH025M_u9H3Ws1gxbHRlGtOykdXqs',
    appId: '1:202435906700:ios:386463caeb43eb6fa23fa9',
    messagingSenderId: '202435906700',
    projectId: 'forpartum-app',
    storageBucket: 'forpartum-app.appspot.com',
    iosClientId: '202435906700-nern3gns142v93b040v8u4ic0o7e3c4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.forpartumadmin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK2FUH025M_u9H3Ws1gxbHRlGtOykdXqs',
    appId: '1:202435906700:ios:386463caeb43eb6fa23fa9',
    messagingSenderId: '202435906700',
    projectId: 'forpartum-app',
    storageBucket: 'forpartum-app.appspot.com',
    iosClientId: '202435906700-nern3gns142v93b040v8u4ic0o7e3c4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.forpartumadmin',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9w7SgvBvrSismWaEchy-iFgk7l-X18oM',
    appId: '1:202435906700:android:eb85cb153c560f54a23fa9',
    messagingSenderId: '202435906700',
    projectId: 'forpartum-app',
    storageBucket: 'forpartum-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT_vTsBBLcvbMjOSejgBk_d1DNhMjfXL8',
    appId: '1:202435906700:web:dd48339a06662c89a23fa9',
    messagingSenderId: '202435906700',
    projectId: 'forpartum-app',
    authDomain: 'forpartum-app.firebaseapp.com',
    storageBucket: 'forpartum-app.appspot.com',
    measurementId: 'G-TGHWF39YSC',
  );

}